glotzerlab/signac

- changelog.txt
- signac/core/attrdict.py
- tests/test_job.py
- tests/test_jsondict.py
Enable deleting of document key-values by attribute, deletion.
For example:
```python
del job.doc.foo
```
We can already "get" values by attribute API, why not delete them as well?
If necessary:
> Enable deleting keys with attr deletion for AttrDict.

- signac/core/h5store.py
- tests/test_h5store.py
* Provide users with more options to control how the underlying h5py.File
is constructed.
* Implemented unit tests that test opening in read- and write-only mode.
It was not possible to control the open mode prior to this patch.
> Expand and forward constructor arguments of H5Store to h5py.File.

- signac/core/h5store.py
- tests/test_h5store.py
Instead of creating an automatic copy.
There are many good reasons for this change in behavior:
1. Creating an automatic copy is the much more dangerous option,
potentially leading to an unexpected copy of terra-bytes of data.
2. Creating an automatic copy is not what a user familiar with h5py
would expect to happen.
3. Creating a hard-link is actually closer to the behavior of standard
in-memory dicts, which would also create a reference instead of a copy
when assigning the same array to multiple keys.
4. With this behavior, the user still has the option to create a copy
if desired, the reverse would not be immediately possible.
The only viable alternative behavior that I see is to not allow assigning
arrays at all, which I find much less appealing.
> Create a hard-link within files when assigning a dataset.

- changelog.txt
- signac/contrib/job.py
- tests/test_job.py
See issue #120 for description.
I also looked at the possibility of chaining calls to `Project`, but there were no candidate methods that I thought would be good to chain.
> Resolve issue #120 by allowing job methods to be chained.

- signac/core/h5store.py
Otherwise it is not possible to override the mode after obtaining the
instance of H5Store.
That is a problem in combination with `job.data` etc.
> Make 'mode' an argument of open() instead of the constructor.

- changelog.txt
- signac/contrib/project.py
> Remove index from Project.find_jobs()

- changelog.txt
- signac/contrib/job.py
- signac/contrib/project.py
- signac/core/dict_manager.py
- signac/core/h5store.py
- tests/test_h5store_manager.py
- tests/test_job.py
Introduces the `DictManager` and the `H5StoreManager` classes that are exposed as `job.stores` and `project.stores`.
It would be highly advantageous to enable users to easily manage multiple HDF5-files instead of just one. There are plenty of reasons why that is a good idea:
1. While the HDF5-format is generally mutable, it is fundamentally designed to be used as an immutable data container. In fact, even the latest version is internally restricted to append-only operations and a file will continue to grow with repeated addition and edits. The only way to reduce the file size is to create a new file (e.g. with `h5repack`).
2. A single large file is difficult to synchronize. Even if we only change a few MBs or even KBs of a multiple TBs-large file, there is a large chance that …
> Implement the H5StoreManager class.

- signac/contrib/collection.py
- signac/core/dict_manager.py
- signac/core/h5store.py
- signac/core/synceddict.py
- signac/errors.py
- tests/test_collection.py
- tests/test_h5store.py
- tests/test_job.py
- tests/test_jsondict.py
The use of an invalid key should lead to the raise of an
InvalidKeyError, which is newly defined in the errors module.
> Elevate all dots-in-keys deprecation warnings to errors.

- changelog.txt
- doc/api.rst
- signac/contrib/job.py
- signac/contrib/project.py
- signac/core/h5store.py
- signac/core/jsondict.py
I added a docstring to the root-namespace exposed JSONDict class and
moved the `parent` constructor argument to the end of the argument
order.
Having the filename be the first argument is much more natural to users
who would want to use this class stand-alone. All internal calls to this
constructor used `filename=...` syntax, so this change does not require
any other changes to the code base.
> Documentation for JSONDict constructor.

- signac/core/json.py
The function `numpy.asscalar` has been deprecated in NumPy 1.16. The [recommended replacement is `numpy.ndarray.item`](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.asscalar.html#numpy.asscalar
), but this only applies to one-element arrays. Since we have a class of type `numpy.number`, just call `o.item()` directly, which is [exactly what the implementation of `asscalar()` does](https://github.com/numpy/numpy/blob/v1.16.1/numpy/lib/type_check.py#L517-L547). 
If necessary:
> Change deprecated numpy.asscalar to o.item()

- changelog.txt
- signac/core/h5store.py
- tests/test_h5store.py
Implements `H5Group.__repr__`.
For example:
```python\
>>> H5Store('data.h5')['foo']
H5Group(store=H5Store(filename='data.h5'), path='/foo')
```
Improves the REPL experience.
> Improve the representation of `H5Group`.

- changelog.txt
- signac/core/jsondict.py
- signac/core/synceddict.py
- tests/test_synced_attrdict.py
We define `__repr__` for `JSONDict` but not its parent `SyncedAttrDict` or its parent `_SyncedDict`:
```python
def __repr__(self):
return repr(self())
```
When I am in the REPL, the statepoint representation is currently not helpful but the document representation is helpful:
```python
>>> job.sp  # is a SyncedAttrDict
<signac.core.attrdict.SyncedAttrDict object at 0x10b858cc0>
>>> job.doc  # is a JSONDict
{'IBZ_sphericity': 0.5235987755982993, ...}
```
If necessary:
> Move repr from JSONDict to _SyncedDict.

- signac/contrib/collection.py
Resolves unclosed file error in #186.
If necessary:
> Ensure that collection file is closed. Resolves #186.

- changelog.txt
- signac/core/synceddict.py
- tests/test_numpy_integration.py
When writing a `numpy.ndarray` to a `_SyncedDict`, the actual data is written to JSON by converting arrays to lists in the `CustomJSONEncoder`. However, the function `_dfs_update` checks that `old[key] == new[key]` and this fails when comparing `numpy.ndarray` to a `_SyncedList`. (See #184 for details.)
When re-opening the job later, the type of the array becomes `_SyncedList` and this problem doesn't show up. The current tests did not catch the problematic behavior for this reason - they did not check the data immediately after assigning the value in `job.document`.
This PR resolves #184.
If necessary:
> Convert NumPy arrays when updating _SyncedDict.

- changelog.txt
- signac/__main__.py
> Keep signac shell command history on a per-project basis.

- changelog.txt
- signac/core/dict_manager.py
The regex was matching files that included the suffix, but did not
necessarily *end* with the given suffix.
The `DictManager` would list dicts with filenames that do not actually end with the given suffix. For example, `mystore.h5` would be listed, but also `mystore.5h.lock`.
If necessary:
> Fix issue in DictManager that would lead to incorrectly listed dicts.

- .circleci/config.yml
- signac/contrib/filterparse.py
- signac/core/json.py
- tests/test_find_command_line_interface.py
> Added JSONDecodeError for rapidjson >= 0.7.1 with fallback to ValueError.

- CONTRIBUTING.md
Extend the contributing guidelines to outline more ways to contribute and also provide guidelines on how to review PRs.
> Extend the contributing guidelines.

- changelog.txt
- signac/common/validate.py
I added a default value of None to the `default_host` in the config object. I also reordered the workspace and project for clarity (since `workspace_dir`) is an optional key.
When requesting high verbosity for any signac command (since essentially everything reads signac.rc), there are a lot of false positives indicating that something is wrong with the configuration because it's expecting a `default_host` key in the `[General]` section and it typically does not find one.
If necessary:
> Default host is typically not present

- README.md
Add badge and section to README.
> Add links to NumFOCUS to README.

- signac/contrib/collection.py
- tests/test_collection.py
> Make lists containing dicts hashable.

- changelog.txt
- signac/__init__.py
- signac/testing.py
- tests/test_project.py
This is related to signac-flow issue https://github.com/glotzerlab/signac-flow/pull/130 and https://github.com/glotzerlab/signac-flow/issues/129, where we decided it makes more sense to break up the data space initialization into signac core and the flow project initialization into flow.
- New feature
If necessary:
> Add function to initialize a test workspace

- signac/contrib/collection.py
- signac/syncutil.py
I used [vulture](https://github.com/jendrikseipp/vulture) to identify dead code paths in signac. This PR removes code paths that could never be reached (after a `raise`).
Removes dead code.
If necessary:
> Remove dead code paths identified by vulture.

- signac/sync.py
the `src`  and `dst` were written vice versa.
Simply the "dst" and "src" were written vice versa. 
- [x ] Documentation update
- [ x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
If necessary:
> slight change in the documentation

- changelog.txt
- signac/contrib/linked_view.py
Added an error message that is raised on Windows when attempting to create a linked view.
Resolves #214.
If necessary:
> Throw descriptive error message for linked views on Windows.

- benchmark.py
- requirements-benchmark.txt
- signac/contrib/job.py
The result message now better represents results when there is both
a speedup and a slowdown independent of the average speedup/slowdown.
> Improve the reporting of benchmark results.

- tests/test_job.py
- tests/test_project.py
Move warning settings to the `setUp` method. Remove old warning catching logic that is no longer actually catching any warnings.
The warning settings were currently having no effect on the tests since they're launched via the unittest module interface. The intended behavior was to cause all `DeprecationWarning`s to error out, which I don't think is the correct behavior because we shouldn't stop testing deprecated behavior until it's actually removed, so I changed the default to ignore `DeprecationWarning` instead and moved it into `setUp` so that it's actually respected. Some of the other warnings catching logic in specific tests was a holdover and is no longer relevant.
If necessary:
> Ignore deprecation warnings when testing

- changelog.txt
- signac/contrib/project.py
- tests/test_project.py
This uses the `Config` class (not to be confused with the new immutable `_ProjectConfig` class or the `ConfigObj` class from which it inherits) to initialize projects.
**Potential breaking behavior:** The `signac.rc` files generated after this change will differ from the previous configuration files by whitespace (spaces around the equals signs). The configs are parsed the same as before.
The previous code didn't work if the project name contained commas. Resolves #251.
If necessary:
> Use Config class to write config during init_project.

- .github/CODEOWNERS
- contributors.yaml
- doc/api.rst
- signac/contrib/job.py
- signac/contrib/project.py
- tests/test_job.py
- tests/test_project.py
Add `id` property to `Job`
Adds `id` as a property of the `Job` class. I also added a test to ensure that it produces the correct string.
Just follows the python trend of using properties instead of getters and setters.
If necessary:
> Add id property for jobs

- .circleci/config.yml
- changelog.txt
- setup.py
- tests/test_project.py
This PR tests signac on Python 3.8. I am not aware of any other configuration needed to officially support Python 3.8.
Resolves #254.
If necessary:
> Add support for Python 3.8

- .circleci/config.yml
- changelog.txt
- requirements-benchmark.txt
- requirements-dev.txt
- signac/__init__.py
- signac/__main__.py
- signac/contrib/__init__.py
- signac/contrib/filterparse.py
- signac/contrib/import_export.py
- signac/contrib/job.py
- signac/contrib/project.py
- signac/contrib/utility.py
- signac/core/dict_manager.py
- signac/core/h5store.py
- signac/core/json.py
- tests/test_collection.py
- tests/test_h5store.py
- tests/test_job.py
- tests/test_project.py
- tests/test_shell.py
We have been releasing packages as "noarch" but there were several incompatibilities with signac on Windows. To the best of my ability, I have corrected these issues so that all tests pass (or are skipped, where necessary).
The issues solved were present in tests and the core codebase, so it wasn't _just_ a testing problem.
The primary issues solved by this PR:
1. Inconsistencies with line separators (`\n` on POSIX, `\r\n` on Windows) and path separators (`/` on POSIX, `\` on Windows -- also backslashes need to be escaped in a variety of places using regular expressions, which made this more complicated).
2. The reverse of (1): in some places, we used `os.path.join` (which uses the platform's path separator) when we actually need forward slashes. This wouldn't have been caught on POSIX …
> Make tests pass on Windows and test Windows on CI

- changelog.txt
- signac/core/synceddict.py
- tests/test_synced_attrdict.py
A number of methods were calling `_convert_to_dict` on `self._data` rather than calling them on `self`. As a result, the member of the underlying dictionary was modified. Actually, we should be able to remove the `dict` branch of `_convert_to_dict` entirely, but that requires resolving #196 first (because that's the only way that branch is accessed). Further changes are probably worth postponing for when we address #249.
Resolves #234.
If necessary:
> Fix usage of _convert_to_dict to avoid modifying nesting SyncedDict objects when calling items or values

- changelog.txt
- contributors.yaml
- signac/contrib/project.py
- tests/test_project.py
Project initialization add a empty Workspace directory if deleted by user.
Solves issue #267 .
If necessary:
> Fixed race condition when workspace is created. Resolves #267

- .deploy.bash
- setup.cfg
Universal wheels include support for Python 2, which we have dropped. Separately from this PR, I plan to manually re-publish the release of 1.3.0 and attempt to remove the py2-compatible wheel.
This PR resolves #273.
If necessary:
> Use python-tag = py3, and disable universal wheels.

- changelog.txt
- signac/__main__.py
- signac/common/configobj/__init__.py
Fixes issue #301.
If necessary:
> Fix import and call related to 'configob.verify'.

- .coveragerc
- setup.cfg
Small package maintenance improvement. We use `setup.cfg` for all supported tools (flake8, bumpversion) except for coverage. This consolidates `.coveragerc` into `setup.cfg`.
> Consolidate .coveragerc into setup.cfg.

- tests/test_shell.py
See #311. A test relied on dictionary order for its output, which failed randomly on Python 3.5.
Resolves #311.
If necessary:
> Don't enforce dictionary ordering in signac diff.

- tests/test_h5store.py
There is a test that fails randomly on CI. This marks it as `xfail`.
@csadorf You might have opinions on this -- is this test valid? I'm not convinced that it's a multithreaded behavior we should be able to rely on, and clearly it fails a lot. I ran it about 20 times on my machine and wasn't able to reproduce the failure.
Examples of failures:
- https://app.circleci.com/pipelines/github/glotzerlab/signac/882/workflows/3c5215d0-2188-4cb7-8f55-edeca6a46fd3/jobs/5728
- https://app.circleci.com/pipelines/github/glotzerlab/signac/875/workflows/cb2c2064-0d90-4ece-bdaf-68927b865c8a/jobs/5668
> Add xfail to multithreaded H5Store test that fails randomly.

- .circleci/config.yml
- changelog.txt
- setup.cfg
- signac/common/errors.py
- signac/common/host.py
- signac/contrib/filterparse.py
- signac/contrib/indexing.py
- signac/contrib/project.py
- signac/core/h5store.py
- signac/core/json.py
- signac/errors.py
- signac/syncutil.py
This is an experimental PR adding types to `signac.core.json`. This was created using [MonkeyType](https://github.com/Instagram/MonkeyType) and modified slightly. Adding type validation seems like a simple process.
To generate this, I installed `monkeytype` and then ran the following commands from the repository root:
```bash
monkeytype run -m pytest -v
monkeytype list-modules
monkeytype stub signac.core.json
monkeytype apply signac.core.json
vim signac/core/json.py
```
We'd need to validate the results with mypy, I think.
Just wanted to try it out.
If necessary:
> Add typing to signac.core.json.

- changelog.txt
- signac/contrib/schema.py
- tests/test_project.py
Added `_repr_html_` method in  `ProjectSchema`
Resolves #314 
If necessary:
> Added pretty representation of ProjectSchema for IPython

- doc/conf.py
- setup.cfg
- signac/contrib/import_export.py
- signac/contrib/project.py
- signac/contrib/schema.py
issue #315 
If necessary:
Change of doc string to `numpydoc` in schema.py
> numpydoc style(signac/contrib/schema.py)

- doc/conf.py
- setup.cfg
- signac/contrib/job.py
issue #315 
If necessary:
Change of doc string to `numpydoc` in schema.py
> numpydoc style(signac/contrib/job.py) 

- signac/contrib/project.py
- tests/test_pandas_integration.py
Add feature for including/excluding state point and document keys from an exported pandas DataFrame.
Resolves #327.
If necessary:
> Add usecols and flatten to to_dataframe feature.

- setup.cfg
- signac/core/attrdict.py
- signac/core/dict_manager.py
- signac/core/h5store.py
- signac/core/json.py
- signac/core/synceddict.py
Applied numpy docstyle to the core submodule.
Part of #315.
If necessary:
> Numpy docstyle for core submodule

- setup.cfg
- signac/contrib/import_export.py
- signac/contrib/job.py
issue #315 
If necessary:
Change of doc string to `numpydoc` in import_export.py
> numpydoc style (signac/contrib/import_export.py)

- setup.cfg
- signac/__init__.py
- signac/__main__.py
- signac/diff.py
- signac/sync.py
- signac/syncutil.py
- signac/testing.py
- signac/version.py
This PR applies NumPy docstyle to remaining files in the `signac` directory (i.e. the level of `__init__.py`).
Progress on #315. After this, remaining PRs should remove `core`, `common`, and `contrib` from the "skipped" directories in `match-dir` in `setup.cfg`.
If necessary:
> Apply NumPy docstyle to remaining files in "signac" root.

- signac/contrib/collection.py
- signac/contrib/filterparse.py
- signac/contrib/import_export.py
- signac/contrib/linked_view.py
- signac/contrib/project.py
- signac/contrib/utility.py
I used a very early-stage tool from @Carreau to lint our NumPy docstrings. https://github.com/Carreau/minirst
It found a few errors in the docstring style. A later-stage "stable" version of this tool could be a helpful CI linter. I will merge this PR immediately when CI passes because the changes are minor.
> Apply fixes from minirst.

- doc/requirements.txt
As [pointed out](https://github.com/glotzerlab/signac/pull/359#issuecomment-671245923) by @csadorf, the build of the documentation [is failing](https://readthedocs.org/projects/signac-core/builds/11587075/) because it doesn't import the dependency we added in #359.
Here's the [project on pypi](https://pypi.org/project/sphinxcontrib-programoutput/) to confirm that it can be installed with `pip install`.
Should we add pre-merge tests for the docs?
If necessary:
> Add missing dependency to doc build

- changelog.txt
- requirements-dev.txt
- tests/test_project.py
This PR changes a small number of tests that relied on the `pytest-subtests` plugin.
The `pytest-subtests` plugin was causing some trouble because upgrades to `pytest` broke compatibility with `pytest-subtests` on two separate occasions:
1. 0.3.1 to 0.3.2 breakage is documented here: #366, https://github.com/glotzerlab/signac/pull/366#issuecomment-676579490.
2. 0.3.0 to 0.3.1 breakage is not documented but I remember running into it on my own, and found a comment to corroborate this on Slack.
If necessary:
> Remove dependency on pytest-subtests.

- doc/api.rst
Documents dict-like methods on JSONDict, H5Store, and inherited methods for H5StoreManager.
After discussion with @DomFijan, we decided we should document dict-like methods on JSONDict and related classes.
If necessary:
> Add inherited members to dict-like classes.

- README.md
This adds Twitter/GitHub stars to the repo badges.
We would like signac users to star the GitHub repository and follow the Twitter account.
> Add Twitter/GitHub stars to badges.

- changelog.txt
- signac/core/h5store.py
This PR adds support for h5py major version 3 and should be merged before #409 (to show that the code functions both before and after the upgrade).
The h5py package changed its default handling of strings in version 3. See this page for info: https://docs.h5py.org/en/latest/strings.html
This PR adds a shim to detect string data, so that it can be returned as `str` and not `bytes`. I tested this locally with h5py 2.10.0 and 3.0.0, and it should work for older versions of h5py as well (that's why I used the older function `check_dtype` instead of `check_string_dtype`, which was added in 2.10).
If necessary:
> Add support for h5py >=3.0.0.

- .circleci/config.yml
- .gitignore
- .pre-commit-config.yaml
- CONTRIBUTING.md
- changelog.txt
- doc/support.rst
- pyproject.toml
- requirements-precommit.txt
- setup.cfg
1. This PR introduces `black` and `isort` for automatically fixing code style.
2. The checks for `flake8`, `pydocstyle`, and `mypy` are the same as before, except they are no longer "local" hooks (they use the pre-commit virtual environment instead).
**I am seeking reviewer feedback on the new configuration before committing reformatted code.**
For an example of what the style looks like, see #416. I applied all the changes in that PR.
1. The development team decided to adopt `black` as a code formatter at the previous developer meeting. I hope this will make the process of development faster as a whole. While there is a nonzero cost to having a pre-commit workflow with many hooks, it is worth it if this kind of change can reduce the number of iterations and "nitpick" style comments …
> Use black and isort, managed with pre-commit.

- changelog.txt
- signac/contrib/job.py
Many methods/properties of `Job` invoke a call to `job.init()`, including the first access to `job.document` and all accesses to `job.stores` and `job.data`.
This PR optimizes `job.init()` for jobs that are already initialized, by exiting early.
This is a performance enhancement for many common data access operations in signac.
Performance results for the script below:
| Test           | `master` | This branch (b4917d8) | Speedup         |
|----------------|----------|-----------------------|-----------------|
| First init     | 3.426s   | 3.546s                | 0.966x (slower) |
| Already init'd | 2.623s   | 1.774s                | 1.479x (faster) |
```python
import signac
project = signac.init_project('test')
for i in range(20000):
project.open_job({'a': i, 'b': i*2, 'c': i*3}).init() …
```
> Attempt to exit early from _init if a job manifest exists and is valid.

- changelog.txt
- signac/contrib/filesystems.py
- signac/contrib/linked_view.py
- signac/contrib/utility.py
Since Python 2 support has been removed, we can replace the internal function `_mkdir_p` with `os.makedirs(path, exist_ok=True)`.
Simplifies internal code. Standard library features should be used where possible.
Cases where _files_ exist with the name for the destination directory raise an error. This was previously caught and tested separately but no longer needs special error handling code.
> Simplify internal function for mkdir -p.

- changelog.txt
- signac/core/jsondict.py
- tests/test_buffered_mode.py
This PR changes the internal behavior of the buffer. When a new item is added to the buffer, the code checks the current buffer load (size of all items in the buffer) and ensures that the current load plus the size of the new item is less than the maximum buffer size. The function that calculates this buffer size appears to consume a lot of time in my profiles of signac-flow projects with 1000 jobs. I made changes that will increment the buffer load after each store, so that buffer size access can be done in constant time.
The buffer load is reset when the buffer is flushed. I did some manual testing to ensure that the size calculations agree during a normal filling and flushing of the buffer.
The profiling I did on signac-flow involved some status checks with label functions that …
> Optimize buffer load checks.

- doc/conf.py
Fix a regression due to auto formatting causing warning in docs build. The error was:
```
$ sphinx-build -b html ./doc ./build/html
Running Sphinx v3.1.1
making output directory... done
WARNING: The config value `author' has type `tuple', defaults to `str'.
Extension error:
Handler <function check_confval_types at 0x7f9275c54158> for event 'config-inited' threw an exception
```
Note I'm not actually sure where author info appears in the built website.
The issue was introduced in commit b67a78dabfb6a367f878e6e3edc7a8ea3193b508 as part of #416 
If necessary:
> fix doc build warning requiring string

- signac/contrib/import_export.py
- signac/contrib/job.py
This should fix some intermittent failures seen on CI. It may need to be run on CI a few times to ensure that this fixes the problem.
See issue #431 for a full description of the issue this aims to resolve.
Fix CI failures relating to POSIX error code handling.
If necessary:
> Raise DestinationExistsError from EEXIST.

- changelog.txt
- signac/core/synceddict.py
The internal function `_dfs_convert` recursively converts containers into their synced equivalents. That is, when reading a state point or document, the `_dfs_convert` function will change a `dict` into a synced dictionary.
**Observation:** Most signac jobs have state points and documents that are relatively flat. That is, most values in a state point or document are common non-container types (string, float, int, bool) and only a few are (dict, list).
I noticed that the code path taken for non-container types must exhaustively test whether the value is a `Mapping`, tuple, list, or NumPy type. Only at the very end it returns the raw value.
Matching the "fast path" to the expected distribution of data is a micro-optimization, but it pays off. Benchmarks are below.
Speeds up all operations …
> Optimize _dfs_convert by exiting early for common types.

- signac/core/__init__.py
- signac/core/synced_collections/__init__.py
- signac/core/synced_collections/buffered_collection.py
- signac/core/synced_collections/collection_json.py
- signac/core/synced_collections/collection_mongodb.py
- signac/core/synced_collections/collection_redis.py
- signac/core/synced_collections/collection_zarr.py
- signac/core/synced_collections/file_buffered_collection.py
- signac/core/synced_collections/synced_attr_dict.py
- signac/core/synced_collections/synced_collection.py
- signac/core/synced_collections/synced_list.py
- tests/test_synced_collections/synced_collection_test.py
- tests/test_synced_collections/test_buffered_collection.py
- tests/test_synced_collections/test_json_collection.py
- tests/test_synced_collections/test_mongodb_collection.py
- tests/test_synced_collections/test_redis_collection.py
- tests/test_synced_collections/test_zarr_collection.py
This PR addresses a number of miscellaneous to-do items associated with the `SyncedCollection` classes. 
- Renames sync to save, which is less ambiguous (sync sounds two-way).
- Converts load and sync to private methods, client code should never have to call them explicitly (synchronization should be transparent).
- Improves constructors so that they can accept positional arguments. Due to the extensive use of multiple inheritance and super calls, the concrete implementation classes need to override init and manually pass the arguments through to ensure that parent classes receive all the right arguments without requiring the user to pass keyword arguments.
- Makes _update an abstractmethod so that it's clear that it must be inherited.
- Makes _backend an abstract property to enforce …
> Feature/synced collection/cleanup

- signac/contrib/project.py
Fixes a typo. I will merge immediately.
> Fix typo in the name of JobsCursor class.

- changelog.txt
- signac/contrib/job.py
- tests/test_project.py
In signac-flow's aggregation feature, it is fairly common to check membership: `job in list(job1, job2, ...)`. This is currently very slow in signac.
By [Python's membership test rules](https://docs.python.org/3.6/reference/expressions.html#membership-test-details), `x in y` is equivalent to `any(x is e or x == e for e in y)`.
Currently, the `__eq__` check requires a call to `os.path.realpath`, which is fairly expensive. For a directory path like `/a/b/c/d/e/f`, `realpath` must check whether `/a`, `/a/b`, `/a/b/c`, etc. are symlinks, and if so, resolve them to their target location. That requires a lot of system calls just to check if jobs are equal. You can see that definition [here](https://github.com/python/cpython/blob/fbc7723778be01b8f3bb72d2dcac15ab9fbb9923/Lib/posixpath.py#L390).
I …
> Optimize job __hash__ and __eq__ checks.

- setup.cfg
- signac/core/synced_collections/buffered_collection.py
- signac/core/synced_collections/collection_json.py
- signac/core/synced_collections/file_buffered_collection.py
- signac/core/synced_collections/synced_attr_dict.py
- signac/core/synced_collections/synced_collection.py
- signac/core/synced_collections/synced_list.py
- signac/core/synced_collections/utils.py
- signac/core/synced_collections/validators.py
- tests/test_synced_collections/synced_collection_test.py
- tests/test_synced_collections/test_json_buffered_collection.py
- tests/test_synced_collections/test_json_collection.py
- tests/test_synced_collections/test_utils.py
This PR optimizes all JSON-based SyncedCollections, including the buffered mode. I benchmarked a number of operations comparing the new JSONDict to the old one on two machines, a 2020 Macbook Pro and our Linux workstations using a slow network file system (as opposed to faster scratch space). I'm happy to share some plots for those interested. Brief summary: depending on the operation being benchmarked, whether buffering is enabled, and the operating system, I see performance improvements in the range of 1.3x-2.7x. In general the biggest performance improvements are observed for operations that change the dict since they touch all of the code paths that I optimized. Some more detailed information:
- Overall I see bigger improvements on the Mac than on the Linux machines. I have not …
> Feature/synced collection/optimization

- changelog.txt
- signac/core/h5store.py
Optimizes the `H5Store` initializer to use `os.path.abspath` instead of `os.path.realpath`. As mentioned in #442, the cost of `realpath` is fairly high and it isn't necessary to use a "real" path in this case.
(Note that this optimization would *not* apply to `job.document` or anything that must interface with signac's buffering logic, in my understanding. Buffering relies on "real" paths to ensure that data is correctly loaded in the buffer.)
Speeds up H5Store initialization.
I noticed this optimization while using a signac-flow project with a condition that checks for a key in `job.data`. For my simple test case with 157 jobs, the time spent in the condition function went from 2.72 seconds to 2.15 seconds (21% faster).
Note: Another 20-30% of the time could be trimmed by adding lazy …
> Optimize H5Store init.

- signac/core/synced_collections/buffered_collection.py
- signac/core/synced_collections/collection_json.py
- signac/core/synced_collections/collection_mongodb.py
- signac/core/synced_collections/collection_redis.py
- signac/core/synced_collections/collection_zarr.py
- signac/core/synced_collections/file_buffered_collection.py
- signac/core/synced_collections/memory_buffered_collection.py
- signac/core/synced_collections/synced_attr_dict.py
- signac/core/synced_collections/synced_collection.py
- signac/core/synced_collections/synced_list.py
- tests/test_synced_collections/synced_collection_test.py
- tests/test_synced_collections/test_json_buffered_collection.py
- tests/test_synced_collections/test_mongodb_collection.py
This PR makes both implemented buffering modes thread-safe. This PR is a best effort attempt at achieving thread safety. There may still be edge cases that I did not catch, and it may be possible in at least some cases to reduce the locking serialization using more narrowly scoped mutexes. However, these changes are resilient to the different error cases that I tested (included as new tests), and since the purpose of buffered mode is to reduce I/O operations, once we're in buffered mode the code will be effectively serialized by Python anyway, so there's limited performance to be regained by allowing multithreaded I/O operations in practical use cases (although there will be edge cases where that's not the case, such as when reading a large number of files once after entering a buffer). …
> Feature/synced collection/thread safe buffering

- changelog.txt
- signac/contrib/job.py
- tests/test_job.py
I caught a couple minor errors in signac-flow tests (to be addressed separately) that were exposed by the changes in #442. This unrelated problem in signac-flow indicated an issue in the new `__eq__` check, which doesn't correctly handle comparisons to non-Job objects. This PR fixes that bug so the `Job` class correctly adheres to the Python data model.
Specifically, the old `__eq__` behavior did nothing to ensure that the objects being tested for equality were Job objects. If a job object and a tuple were compared, the previous `Job` equality test just checked if `hash(job) == hash(tuple_of_data)`, which hid the test failures in signac-flow until #442 was merged and errors were raised by the comparison. However, the comparison _should not_ raise errors or return `False`, and should …
> Handle non-Job objects in Job equality check.

- signac/contrib/job.py
- tests/test_job.py
- tests/test_project.py
The (unreleased) lazy loading code recently introduced in #239 and/or #451 appears to delete invalid state point files if the state point on disk is invalid AND `job.init()` is called before `job.statepoint`. In my understanding, the only case where a state point file should be deleted is if the initial file creation/write operation fails during `job.init()`.
If necessary:
> Fix: don't delete invalid statepoints

- changelog.txt
- signac/core/synceddict.py
- tests/test_numpy_integration.py
Adds support for zero-dimensional NumPy arrays like `numpy.array(1.0)`.
I note that this is _not_ a problem in our JSON encoder, only in `_dfs_convert` because it assumes that all NumPy arrays can be used to construct a SyncedList (which is not true for 0-d arrays, since SyncedLists must be 1-d or higher).
Resolves #476.
If necessary:
> Add support for zero-dimensional numpy arrays.

- signac/__init__.py
- signac/contrib/errors.py
- signac/contrib/hashing.py
- signac/contrib/import_export.py
- signac/contrib/job.py
- signac/contrib/project.py
- signac/core/synced_collections/buffered_collection.py
- signac/core/synced_collections/collection_json.py
- signac/core/synced_collections/collection_mongodb.py
- signac/core/synced_collections/collection_redis.py
- signac/core/synced_collections/collection_zarr.py
- signac/core/synced_collections/serialized_file_buffered_collection.py
- signac/core/synced_collections/synced_attr_dict.py
- signac/core/synced_collections/synced_collection.py
- signac/core/synced_collections/synced_list.py
- signac/core/synced_collections/utils.py
- tests/test_buffered_mode.py
- tests/test_job.py
- tests/test_synced_collections/synced_collection_test.py
- tests/test_synced_collections/test_utils.py
This PR integrates the new synced collections into the core of signac. The job and project documents as well as the job statepoint now use the new classes. As part of the change, I also cleaned up parts of the Job class and removed basically all of the internal methods, many of which were quite small or only called once. The new classes are seamless fits for the job and project documents, I was able to perform basically a drop-in replacement. The statepoint is a little bit trickier, because it violates some of the core assumptions of how you'd expect SyncedCollections to typically work. A list (not necessarily exhaustive) of relevant points:
1. Statepoints almost never load from disk because they rely on data provided at initialization whenever possible (possibly from the project cache) …
> Feature/synced collection/replace jsondict

- signac/__init__.py
- signac/synced_collections/buffers/buffered_collection.py
- signac/synced_collections/buffers/file_buffered_collection.py
- tests/test_buffered_mode.py
- tests/test_synced_collections/test_json_buffered_collection.py
Removes global buffering of synced collections in favor of class-specific buffering.
The current version of global buffering affects all backends simultaneously. This implementation doesn't really make sense; users should only be controlling buffering on a per-backend basis. The new approach also simplifies the process of introducing backend-specific buffering behavior, in this case for the purpose of reintroducing support for buffer size as a parameter for the buffering context.
If necessary:
> Feature/synced collection/simplify global buffering

- signac/core/attrdict.py
- signac/core/jsondict.py
- signac/core/synceddict.py
Deprecates the _SyncedDict, SyncedAttrDict, and JSONDict classes from signac. Currently does not include any information regarding replacements, we can add if someone feels strongly about that, or we can wait until we decide how synced_collections will look.
If necessary:
> Feature/synced collection/deprecate old

- changelog.txt
- signac/contrib/filterparse.py
- signac/contrib/import_export.py
- signac/contrib/linked_view.py
- signac/contrib/project.py
- signac/contrib/schema.py
- tests/test_find_command_line_interface.py
- tests/test_project.py
- tests/test_shell.py
This PR undoes the reversion in #499, which reverts #332. The `JobsCursor` constructor is _not_ public API, so breaking it should be acceptable and no additional tests are necessary. Unfortunately, the most recent release of signac-flow makes use of this API internally, which is why this problem was identified. I'll make a subsequent PR to add a compatibility layer for this, and a separate PR in signac-flow to resolve the improper API usage for future versions of signac-flow.
> Revert "Revert "Implement feature to search jobs with a sp- and doc-integrated filter ""

- signac/synced_collections/backends/collection_json.py
- signac/synced_collections/backends/collection_mongodb.py
- signac/synced_collections/backends/collection_redis.py
- signac/synced_collections/backends/collection_zarr.py
- signac/synced_collections/data_types/synced_collection.py
Remove `add_validator` and instead force classes to define validators at class definition time via clearly defined class variables.
This change prevents issues that could arise if different applications using synced collections try to register different validators to the same SyncedCollection class, because there is no way to namespace these if they can modify the class directly. The change forces users to subclass the desired class to add the new validators.
This change also allows reliable registration of validators at class-definition time, rather than collection of validators from the MRO every time the property is requested. This is a minor optimization. More importantly, the addition of the resulting `_all_validators` hook makes it easy for subclasses to override the set list of …
> Remove add_validators and specify validators in class definition

- signac/synced_collections/data_types/synced_collection.py
- signac/synced_collections/data_types/synced_dict.py
- signac/synced_collections/data_types/synced_list.py
Currently `_validate` is called on any container type, then again for each of its elements when `_from_base` is called on that element. This patch removes that extra call.
Optimization for synced collections.
If necessary:
> Feature/synced collection/disable recursive validation

- signac/contrib/job.py
- signac/synced_collections/backends/collection_json.py
- signac/synced_collections/data_types/attr_dict.py
**This PR should be merged after #508.**
It changes the `_PROTECTED_KEYS` attribute of AttrDict subclasses into sets to speed up checks for when those are being accessed. It also changes the order of checks in __setattr__ assuming that dunder attributes are set far less frequently than protected keys.
Optimization for synced collections.
If necessary:
> Feature/synced collection/optimize protected key lookup

- signac/contrib/job.py
- signac/synced_collections/data_types/synced_dict.py
- tests/test_job.py
@vyasr this is an attempt to defer instantiation of the `_StatePointDict` class. Related to https://github.com/glotzerlab/signac/pull/484#issuecomment-774398330.
~I also added an option to disable input data validation in `SyncedCollection._update`.~ I am moving the option to disable data validation into a separate PR.
Speeds up `Project.open_job` by deferring `_StatePointDict.__init__` until `Job.statepoint` access.
This is a performance improvement for common access patterns (project iteration) for the same reasons as lazy loading, but benchmarks measuring "time to read statepoints" will see no change.
With deferred instantiation of the `_StatePointDict`, the profile of `open_job` looks identical for the current state of PR #484 and v1.6.0. As a consequence, we can conclude that the …
> Defer statepoint instantiation, unify reset_statepoint logic

- changelog.txt
- signac/contrib/project.py
I have been running benchmarks for synced collections (#484) and noticed that my project was loading state point data even when not requested.
I traced this down to the recent changes in #332 that changed the default `filter` behavior from `None` to `{}`. This prevented some of the "fast path" checks from triggering, and caused a full index for the project to be constructed.
Bug fix.
I don't know how to test this effectively, because it only affects internal APIs and performance, not correctness.
If necessary:
> Treat empty filters {} the same as None.

- signac/contrib/job.py
- signac/synced_collections/data_types/synced_dict.py
- signac/synced_collections/data_types/synced_list.py
Split off from work started in #497. This PR allows data validation to be skipped on state point load, by adding an option `_validate=False` to the SyncedCollections' `_update` method.
Trying to get SyncedCollection performance closer to the performance on `master` by shaving off checks that might not be necessary (based on the current balance of safety/performance in signac).
If necessary:
> Optionally skip validation in SyncedCollection _update.

- changelog.txt
- signac/contrib/job.py
- signac/contrib/project.py
Extends on work started in #511. In a few performance-critical locations that use internal paths (not user-provided paths), we can sacrifice the safety benefits of `os.path.join(*paths)` in favor of the speedier `os.sep.join(paths)`.
This yields about a 20-25% speedup when iterating over a project without accessing job state points.
We can only apply this optimization in places that deal with _internal paths_, like "project_workspace / job_id" but not like `job.fn(some_user_path)`. User paths must be accessed through `os.path.join`, which includes the project workspace (which is configurable). Regardless, we are able to safely handle the most important cases (the job workspace and the job state point filename) that are called O(N) times.
Below I have benchmarks of the following script, …
> Optimize path joins with os.sep.join(...).

- signac/synced_collections/data_types/synced_collection.py
Add locks needed to avoid deadlocks in `SyncedCollection`
This MWE deadlocks because `SycedCollections._locks[lock_id]` gets overwritten while it is being used:
```
import json
import tempfile
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
from signac.synced_collections.backends.collection_json import JSONAttrDict
def update_status(data):
s, filename = data
d = JSONAttrDict(filename=filename)
d.update(dict(a=1, b=s-1))
return False
if __name__ == "__main__":
N = 1
n_tasks = 20
with tempfile.TemporaryDirectory() as d:
for s in range(N):
with open(f'{d}/{s}.json', 'w') as f:
json.dump(dict(a=s, b=0), f)
tasks = []
for s in range(N):
for t in range(n_tasks):
tasks.append((s, f'{d}/{s}.json'))
with ThreadPoolExecutor() as e:
e.map(update_status, tasks) …
```
> Avoid deadlock in SyncedCollection

- changelog.txt
- signac/contrib/job.py
- signac/contrib/project.py
While debugging #528, we identified two sets of changes that are needed for correctness.
This PR adds thread locks around Job and Project methods that lazily instantiate synced collections and HDF5 data stores.
Fixes thread safety in Job and Project classes.
If necessary:
> Lock lazy properties

- .circleci/config.yml
I recently enabled pre-commit CI. This can replace the pre-checks currently being run on CircleCI.
Removes redundancy and potentially speeds up CI.
If necessary:
> Skip pre-checks in favor of pre-commit CI.

- signac/__main__.py
- signac/contrib/migration/__init__.py
This PR fixes some minor issues I found while implementing glotzerlab/signac-flow#504.
These bug fixes have no impact right now because migrations are not enabled, but they will be needed once the migration code path is activated.
If necessary:
I don't think a changelog entry is warranted for this PR.
> Fix bugs in schema code

- changelog.txt
- signac/contrib/job.py
- signac/contrib/project.py
See #506 for issue description. This alters a docstring whose described behavior doesn't match the implementation.
Resolves #506.
If necessary:
> Fix incorrect docstring, resolve #506.

- benchmark.py
- doc/api.rst
- signac/contrib/job.py
- tests/test_buffered_mode.py
Part of removing deprecated code for v2.0
get_id() was the only deprecated function in job.py and was easy to pull out/ replace.
If necessary:
> Remove deprecated job.get_id() 

- tests/test_synced_collections/test_validators.py
This is a minor fix for an issue in a test of synced collections with data types that cannot be serialized.
The current test uses `numpy.complex`, which is an alias for the built-in type `complex`. This test should instead use `numpy.complex128`, which is the scalar type that was intended for this test of unsupported NumPy types.
Removes a warning from the output of `pytest`.
If necessary:
> Fix warning in synced collections tests with complex value.

- signac/syncutil.py
Removes `signac.syncutil.copytree`, originally deprecated in #432, #439.
Part of signac 2.0 API cleanup.
If necessary:
> Remove syncutil.copytree

- signac/__main__.py
- signac/contrib/project.py
- signac/contrib/utility.py
- tests/test_project.py
This PR removes unused utility functions and cleans up test coverage of the `utility.py` module.
Notes:
- The `_query_yes_no` function doesn't need test coverage (it's strictly for interactive use on the terminal).
- The `_split_and_print_progress` function can probably be simplified and replaced with tqdm, if it is needed at all. The function is used only once, to print info-level logging for updates to the in-memory state point cache. This should be investigated further, but I've made the function private for now.
- There was an important edge case of `_nested_dicts_to_dotted_keys` that wasn't being tested, when a value is an empty dict. I added a test that covers that edge case.
Cleanup for signac 2.0.
<sup>1</sup>The change breaks (or has the potential to break) existing …
> Clean up utility functions.

- signac/contrib/collection.py
- signac/contrib/linked_view.py
A few smaller commits that I forgot to push to #597. I am going to merge this immediately since it's just removing private functions that are never called internally (I found them by looking over test coverage, and verified that the functions are never used).
> Remove unused functions.

- signac/common/errors.py
- signac/errors.py
Removes unused error classes from signac 2.0.
If necessary:
> Remove unused error classes.

- changelog.txt
- signac/contrib/project.py
Following conversation on #197, I am creating this PR to deprecate methods for state point backup files.
https://github.com/glotzerlab/signac/issues/197#issuecomment-786925614
Once this PR is merged into `master`, we should merge `master` into `next`. Then we can tackle changes from this PR (removing `read_statepoints`, `write_statepoints`, `dump_statepoints` and some corresponding changes in behavior) in a new PR to `next`.
Reducing the API to core features for signac 2.0 in alignment with discussion on #197.
If necessary:
> Deprecate state point backup files.

- changelog.txt
- signac/contrib/project.py
addresses issue #588 
Indexing is deprecated and we'd like to remove `indexing.py` in v 2.0, but to do so we need to remove dependencies in `project.py`.
If necessary:
> deprecate Project.index

- changelog.txt
- signac/contrib/project.py
Deprecates `JobSearchIndex` class. This class is unused. See #587. I will merge once tests pass.
If necessary:
> Deprecate JobSearchIndex class.

- doc/api.rst
- setup.cfg
- signac/__main__.py
- signac/contrib/filterparse.py
- signac/contrib/import_export.py
- signac/contrib/linked_view.py
- signac/contrib/project.py
- tests/test_project.py
Additional cleanup related to #588. This PR removes `index` arguments from a number of methods of `Project` and the CLI.
I also removed the public methods `read_statepoints`, `write_statepoints`, and `dump_statepoints` from the public API (see #579).
Finally, I removed the deprecated function `get_statepoint` from the public API because it used `FN_STATEPOINTS` which was removed as a part of the previously mentioned `read/write/dump_statepoints` changes. I would have split this into two pull requests but there would have been a couple annoying merge conflicts. Since this is a pure removal, I thought it would be fine to combine the two sets of changes to avoid having to deal with the conflicts.
Deprecations for the `index` argument will need to be added to signac 1.x.
signac 2.0 API …
> Remove index arguments and state point backups

- doc/api.rst
- signac/contrib/project.py
- tests/test_project.py
Remove deprecated groupbydoc method and consolidate tests.
If necessary:
> Remove groupbydoc.

- setup.cfg
- signac/contrib/project.py
- tests/test_job.py
- tests/test_jsondict.py
- tests/test_project.py
- tests/test_shell.py
I fixed the handling of warnings in signac's tests. Warnings were being globally ignored, which wasn't intended (the warning filters were declared in specific tests but were being applied globally by pytest during test collection). I fixed that by removing the global warning filters and replacing them with warning filters applied to each test. I made sure to include enough of the warning text so that the word "deprecated" was included, to make it easier to find and remove those filters when appropriate.
I separated these changes from PR #586.
If necessary:
> Fix deprecation warnings

- signac/contrib/project.py
- tests/test_project.py
Removes the long-deprecated `JobsCursor.next` method (deprecated since before 1.0).
If necessary:
> Remove JobsCursor.next.

- changelog.txt
- signac/cite.py
We are deprecating and removing the `cite` module in signac 2.0. Resolves #592.
If necessary:
> Deprecate cite module.

- changelog.txt
- signac/contrib/job.py
- signac/contrib/project.py
- tests/test_job.py
- tests/test_project.py
This PR makes the `Project.config` immutable. Follows up on #246 with the planned changes for signac 2.0.
To-do:
See #244 for a discussion where the decision was made to have an immutable Project configuration.
If necessary:
> Disallow Project.config mutation

- doc/requirements.txt
- signac/__init__.py
- signac/synced_collections/buffers/buffered_collection.py
- signac/synced_collections/buffers/file_buffered_collection.py
- tests/test_buffered_mode.py
This alters a couple method signatures and method names for buffering. These changes make signac's buffering consistent with the new names designed by @vyasr in the synced collections submodule.
Executing planned API changes for signac 2.0.
If necessary:
> Update buffer capacity methods for consistency with synced collections

- changelog.txt
- signac/core/h5store.py
- tests/test_h5store.py
- Fix and test H5store.mode property.
- Add some missing tests for H5Store and H5Group.
The `H5Store.mode` property wasn't tested and did not work correctly. I added a few more tests for features that were not executed in the test coverage.
If necessary:
> Fix H5Store.mode.

- changelog.txt
- signac/contrib/import_export.py
- signac/contrib/project.py
- signac/contrib/utility.py
- signac/synced_collections/_caching.py
- tests/test_synced_collections/test_mongodb_collection.py
- tests/test_synced_collections/test_redis_collection.py
There are a few places where signac raises `AssertionError` as a way to validate program state via `assert` statements. This is not a good practice, because "optimized" execution of Python will ignore these assertions, potentially leading to unwanted or invalid program states. See also: https://stackoverflow.com/questions/9929456/keeping-assert-despite-the-o-optimize-flag
Makes some internal logic more resilient if executing Python with optimization flags.
If necessary:
> Avoid AssertionError.

- tests/test_shell.py
This fixes a minor annoyance: after the signac tests run, there is a key `b = c` in the global configuration `$HOME/.signacrc`. This is from a test of the CLI. I modified the test to make a backup of the global configuration and revert changes to the configuration file after the test completes.
If necessary:
> Revert modifications to global configuration file after test completes.

- .gitignore
- .pre-commit-config.yaml
- README.md
- asv.conf.json
- benchmark.py
- benchmarks/benchmarks.py
- changelog.txt
- doc/support.rst
- signac/core/h5store.py
This PR uses [asv (airspeed velocity)](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#setup-and-teardown) to measure performance of the signac package. It could replace our existing `benchmark.py` script. I haven't yet tried all the features of asv, but it does a lot of things we care about and is a very powerful / helpful tool:
- isolated testing of each commit in a virtual environment (which it handles for you)
- automated testing from git ranges: running `asv run v1.3.0..master` tests every commit from v1.3.0 to master (with the current commit's set of benchmarks, so it doesn't require any git trickery!)
- publishing results into a static HTML site that can be hosted/shared: `asv publish`
- local preview of the HTML site: `asv preview`
- checking that the benchmark suite …
> Feature: Measuring the airspeed velocity of an unladen signac

- .circleci/config.yml
- changelog.txt
- requirements/requirements-test-optional.txt
I received a notification from CircleCI that this project depends on a deprecated Xcode image. See https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions for currently supported versions. This PR updates to the latest supported version so that we may continue testing on macOS.
Fixes deprecated CI configuration. No changelog entry required.
If necessary:
> Update deprecated Xcode image from 11.3.0 to 13.2.0.

- signac/contrib/collection.py
- signac/contrib/project.py
- tests/test_project.py
This PR simplifies the internal indexing behavior by eliminating some functions (`Project._index`, `Project._sp_index`) and internal caches (`Project._index_cache`) with behavior that is nearly-equivalent to other functions (`Project._build_index`) and internal caches (`Project._sp_cache`). See comments below. I'm opening this for review but need to make a final pass for changelog, etc.
If necessary:
> Simplify internal indexing

- signac/contrib/project.py
Fixes issue in the docs caught by @rskye144. The argument to `groupby` needs to be wrapped in a tuple if multiple keys are provided.
Fixes docs.
If necessary:
> Fix typo in groupby docstring.

- changelog.txt
- signac/contrib/import_export.py
- signac/contrib/linked_view.py
- tests/test_project.py
- tests/test_shell.py
Just the bug fix.
There is some duplicate code, but that will be refactored in the rest of #642.
see #642 for a description
If necessary:
> Raise error on underspecified path for import/export and view

- changelog.txt
- signac/contrib/collection.py
- tests/test_collection.py
While working on removing internal usage of the `Collection` class in #667 for signac 2.0, I wanted to improve the test coverage for the `Collection` class's find methods to ensure that the new code in signac 2.0 does not introduce bugs/regressions.
I fixed one bug when searching by the primary key (an `AssertionError` was raised unexpectedly when searching for an id that did not exist, when the result should just be an empty set). Additionally, I expanded test coverage of several other features relating to search operators like `$and` and `$type`. I also fixed some mistakes/omissions in the class documentation.
These tests will be used to improve #667 and ensure that we have greater coverage of our `find` API in the smaller Collection-like class in that PR.
<sup>1</sup>The change breaks …
> Improve test coverage of Collection class's find methods.

- signac/__main__.py
- signac/common/config.py
- signac/contrib/migration/__init__.py
- signac/contrib/migration/v1_to_v2.py
- signac/contrib/project.py
- signac/version.py
- tests/test_project.py
- tests/test_shell.py
This PR contains the first components of a migration to schema version 2. The primary change in this PR is that the config file for a signac project has been moved to ".signac/config" rather than "signac.rc". ".signacrc" is no longer supported except as the global configuration file. Additionally, root discovery via `load_config` no longer checks for the presence of the "project" key in a config file to determine the project root. Any directory containing ".signac/config" file is sufficient to terminate the search and establish a project root directory.
Contributes to #197. Part of schema 2 changes.
If necessary:
> Initial migration to schema version 2 including config rename

- tests/test_shell.py
This splits a test for `signac config verify` so that the parts not requiring pymongo can be executed independently.
Improves testing. @vyasr had asked me about tests for `signac config verify` a while back and I had these changes stored locally.
If necessary:
> Split test for signac config verify.

- signac/__main__.py
- signac/contrib/project.py
- tests/test_diff.py
- tests/test_job.py
- tests/test_project.py
- tests/test_shell.py
- tests/test_sync.py
This PR removes the ability for users to set a project name. The name still exists, but it is always just "project". These changes were split off from #643. Currently this changeset only includes the minimal set of changes to ensure that tests pass, but a large number of tests will now trigger warnings. Once reviewers indicate their approval of the new API I can go through and clean up tests.
Specifically, the changes here ensure that in 2.0 a user who accidentally passes a project name as either a positional or keyword argument will only see a warning, not an error. This choice is intended to provide a softer off-ramp for project names since they have been an integral part of signac since its inception. The only cases that were previously valid that will now fail are if the user provides …
> Remove user-provided project name from API

- signac/contrib/migration/__init__.py
- signac/contrib/project.py
- signac/version.py
- tests/test_project.py
This PR changes schema versioning to use a integer version numbers rather than semantic versioning-style strings.
Version strings as used to denote different "levels" of changes are not really applicable to schema. There is no concept of a patch, and while in principle we could make backwards compatible minor changes in practice we only anticipate major-like changes. Switching to this scheme will avoid presenting this extra complexity as we introduce further migrations, and as a bonus it simplifies our internal migration logic. #684 contains more information.
If necessary:
> Use integer schema version numbers

- signac/__main__.py
- signac/common/validate.py
- signac/contrib/migration/__init__.py
- signac/contrib/migration/v1_to_v2.py
- signac/contrib/project.py
- tests/test_project.py
- tests/test_shell.py
This PR updates the v1 to v2 schema migration to remove project names and store preexisting ones in the project document.
Resolves #541. Part of the changeset of #643.
If necessary:
> Remove project name from schema

- changelog.txt
- signac/contrib/project.py
Fixes issues as described by @vyasr in Issue #687 as we tend to change the DeprecationWarning to FutureWarning instead.
The main motivation of this change is basically that warnings of the deprecated features are visible to the users as in current scenarios of Deprecated warnings python hides these by default.
If necessary:
> Use FutureWarning instead of DeprecationWarning in project.py

- changelog.txt
- signac/contrib/import_export.py
- signac/contrib/project.py
- tests/test_project.py
This PR removes support for custom `Job` subclasses defined in custom `Project` subclasses.
This feature is inadequately tested, difficult to maintain, and inefficient compared to the default `Job` class where we can exploit the known behavior of functions like `job.workspace()`. This feature is also not used to the best of my knowledge.
Resolves #588.
If necessary:
> Remove support for custom job subclass

- signac/contrib/project.py
- tests/test_shell.py
The Project constructor no longer requires a config object. Projects are constructed using a root directory alone.
Part of #643. Since projects no longer have ids and are entirely identified by their root directory in signac 2.0, the constructor can be simplified to reflect that.
If necessary:
> Change Project constructor to use root directory

- tests/test_synced_collections/synced_collection_test.py
When multithreading support is disabled, it is possible for operations on synced dicts to fail with a KeyError (as well as the other errors that were already being caught), so the multithreading test now catches that failure. Note that this is a bug in the test only, not in signac itself.
PyPy3 tests of multithreading have been failing due to this omission (see #705 and #706). Additionally, once this failure occurs, the buffer is in an invalid state, so future multithreading tests can fail in unpredictable ways. I reproduced the issue by running `test_json_buffered_collection.py::TestBufferedJSONDictWriteConcern::test_multithreaded` using pytest-repeat to run the test 100 times. I invariably observed failures within this number of tests. I then verified that catching the KeyError and …
> Catch KeyError as another possible failure of multithreading

- signac/__main__.py
- signac/contrib/migration/v1_to_v2.py
- signac/contrib/project.py
- tests/test_project.py
This PR moves the shell history and state point cache files into the .signac directory.
Resolves #197. I have intentionally chosen to do nothing with `signac_statepoints.json` since that file would only have been created by users actually calling the `write_statepoints` function and therefore I think we should leave it to users to delete that file if it is present.
If necessary:
> Move internal signac files into .signac subdirectory

- .circleci/ci-oldest-reqs.txt
- .circleci/config.yml
- changelog.txt
- requirements/requirements-test.txt
This PR adds the plugin [pytest-xdist](https://pypi.org/project/pytest-xdist/) to run tests in parallel. Each CircleCI machine has two cores. This cuts off around 45 seconds from each CI job, which adds up to a decent amount of time across all jobs. The output is a little more verbose.
Before:
After (ignore pypy, I pushed another commit before it finished):
Might as well use all of the CI resources we are given. Saves a bit of time and probably reduces the energy needed by the server since it can sleep sooner.
If necessary:
> Run tests in parallel with pytest-xdist.

- .github/PULL_REQUEST_TEMPLATE.md
This makes all checkboxes required by adding an "or" to the ones that were previously under a separate heading of "if necessary".
[test of relative link](../tree/master/doc)
I propose creating a label for possibly breaking changes.
This PR uses the new template **before reviews**
glotzerlab/signac-flow/pull/508 was merged with unchecked boxes. It will be easier to catch this if we don't use checkboxes as radio buttons or otherwise optional items.
> Allow PR template to catch incomplete tasks

- signac/common/configobj/__init__.py
- signac/contrib/indexing.py
- signac/synced_collections/backends/collection_json.py
- signac/synced_collections/buffers/file_buffered_collection.py
- tests/conftest.py
- tests/test_project.py
- tests/test_synced_collections/test_json_collection.py
Fixes issues as described by @vyasr in Issue https://github.com/glotzerlab/signac/issues/687 as we tend to change the DeprecationWarning to FutureWarning instead.
The main motivation of this change is basically that warnings of the deprecated features are visible to the users as in current scenarios of Deprecated warnings python hides these by default.
If necessary:
> Use `FutureWarning` instead of `DeprecationWarning`.

- signac/__main__.py
- signac/common/config.py
- signac/common/validate.py
- signac/contrib/project.py
This PR removes the local vs global search option from `config.load_config` API in favor of a separate function to handle discovery. It also removes the `project_dir` key that was previously being automatically populated into the config when calling `load_config`.
Populating the `project_dir` key is an unexpected side effect since it adds a key that doesn't actually exist in any config file. One option would be to change `load_config` to return a tuple containing `(root, config)` instead of just the config, but that mixes two distinct pieces of functionality and also makes config loading more expensive than it needs to be. By separating the two functions, calling code can find the config file and load it separately.
<sup>1</sup>The change breaks (or has the potential to break) existing …
> Move discovery to separate functions.

- .circleci/ci-oldest-reqs.txt
- changelog.txt
- requirements.txt
- requirements/requirements-benchmark.txt
- setup.py
- signac/cite.py
- signac/common/config.py
- signac/common/connection.py
- signac/common/crypt.py
- signac/common/host.py
- signac/contrib/filesystems.py
- signac/contrib/indexing.py
- signac/contrib/job.py
- signac/contrib/mpipool.py
- signac/contrib/utility.py
- signac/core/json.py
- signac/core/jsondict.py
- signac/core/synceddict.py
- signac/core/utility.py
- signac/db/database.py
- signac/syncutil.py
- tests/test_buffered_mode.py
- tests/test_db.py
- tests/test_indexing.py
This follows up on PR #716 to apply the vendored `@deprecated` decorator to all code. This requires a change of the tests, which should now expect a `FutureWarning` to be raised instead of a subclass of `DeprecationWarning`.
Note: _We expect CI to fail_ at the benchmarks stage for the CI jobs that execute benchmarks. The benchmarks compare to `origin/master`, which still has a requirement for `deprecation` until this PR is merged. Once this PR is merged, then `origin/master` will no longer depend on `deprecation` and the CI benchmarks will run as usual for future PRs. The CI benchmarks have been removed in the `next` branch with PR #683, so this isn't a long term concern.
Step towards resolving #687.
> Replace deprecation decorator with vendored deprecation decorator for FutureWarnings

- signac/__main__.py
- signac/common/validate.py
- signac/contrib/migration/v1_to_v2.py
- signac/contrib/project.py
- tests/test_job.py
- tests/test_project.py
This PR removes the functionality for users to use a custom workspace directory. Going forward, the workspace will always be an immediate subdirectory of the project called "workspace".
Resolves #390.
> Remove configurable workspace directory 

- changelog.txt
- signac/__main__.py
- signac/contrib/job.py
- signac/contrib/project.py
- signac/contrib/schema.py
- signac/sync.py
- tests/test_job.py
- tests/test_project.py
- tests/test_shell.py
- tests/test_temporary_project.py
This PR removes the various backwards compatibility layers that have been introduced on next to mitigate the pain of migrating to signac 2.0. Some other deprecated code that has previously slipped through the cracks is removed as well.
Based on discussions in some recent PRs (primarily #685 and #714) as well as more extended consideration in [our developer meeting](https://github.com/glotzerlab/signac/wiki/Developer-Meeting-Minutes#2022-04-05), we have decided against including backwards compatibility layers signac 2.0. Previously, we had incorporated some level of compatibility for changes that we foresaw having a particularly wide impact, but per our more recent discussions we will be moving forward with making these changes breaking in 2.0 since none of them are very difficult for …
> Remove compatibility layers and other deprecated code

- signac/common/host.py
This PR prevents signac from emitting warnings when it creates a deprecated SimpleKeyring object on import because it is a module-level constant in the deprecated db module.
We shouldn't be surfacing warnings to the user that are expected consequences of normal signac usage. This issue will disappear when we actually remove the deprecated code in 2.0
> Catch warnings on creation of deprecated password cache.

- benchmarks/benchmarks.py
- changelog.txt
- signac/__main__.py
- signac/common/config.py
- signac/contrib/job.py
- signac/contrib/project.py
- signac/sync.py
- tests/test_diff.py
- tests/test_job.py
- tests/test_project.py
- tests/test_shell.py
- tests/test_sync.py
> Rename `root` parameter to `path`.

- signac/contrib/project.py
While working on #763, I updated the docs for `get_project` and `get_job` to make them sound more similar. I also unified the docs of the free function `signac.get_project` and the class method `Project.get_project` (and similarly for `get_job`).
I also removed an unused helper function `_skip_errors` located in the same file.
> Update docs for get_project and get_job.

- signac/contrib/import_export.py
- signac/contrib/project.py
While working on #763, I unified the `copytree` docs and default parameter behavior across the codebase. Now, the default parameter in public APIs should always be `None` and we should consistently document that `None` means that signac will use `shutil.copytree`.
I also updated a few docstrings related to synchronization.
> Fix copytree docs and unify default parameter logic.

- signac/__main__.py
- signac/contrib/filterparse.py
- signac/contrib/migration/__init__.py
- signac/contrib/utility.py
- tests/test_find_command_line_interface.py
Refactors and simplifies code printing to `sys.stderr`. This eliminates some helper functions and reduces imports.
Found opportunity for simplification while looking at internal documentation. No changelog entry is needed because this does not touch public APIs.
> Refactor and simplify code printing to stderr.

- signac/contrib/utility.py
This PR refactors a utility function `_nested_dicts_to_dotted_keys` to remove a default parameter that is never used by any callers. This simplifies the logic and removes unnecessary functionality. Because this is an internal change, no changelog entry is needed.
> Always encode nested dicts.

- contributors.yaml
- signac/__main__.py
- tests/test_shell.py
I changed the CLI `view` argument to establish a path to be a flag rather than a positional argument. Added a test to check this change and altered another test that had `signac view view path` and changed it to just `signac view path`.
Fixes issue #653.
> Changed CLI View Prefix

- changelog.txt
- doc/api.rst
- signac/contrib/project.py
- signac/core/errors.py
- signac/core/h5store.py
- signac/errors.py
This PR revises the documentation for the `H5Store` class. A few pieces of its docs were missed in the conversion to NumPy documentation style and/or were missing from the API docs.
Clean up for signac 2.0.
> Improve H5Store docs

- changelog.txt
- contributors.yaml
- setup.py
* Remove upper bound of Python 4 on `python_requires` as advocated for in Henry Schreiner's blog post "[Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/)". 
This change follows best practices for libraries and frameworks as generally recommended by the PyPA.
Resolves #780
> [MNT] Remove upper bound on python_requires

- changelog.txt
- signac/__main__.py
- signac/core/dict_manager.py
- signac/core/h5store.py
- signac/core/utility.py
- signac/syncutil.py
- tests/test_project.py
- tests/test_synced_collections/synced_collection_test.py
- tests/test_synced_collections/test_json_buffered_collection.py
Fixes a bug where relative paths crossing drives cause failures on Windows. Example:
```python
>>> # Starting from a current working directory in C:\Users\bdice
>>> import signac
>>> h = signac.H5Store(r"C:\data.h5")
>>> repr(h)
"H5Store(filename='..\\\\..\\\\data.h5')"
>>> h = signac.H5Store(r"D:\data.h5")
>>> repr(h)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "c:\users\bdice\code\signac\signac\core\h5store.py", line 341, in __repr__
type(self).__name__, repr(os.path.relpath(self._filename))
File "C:\Users\bdice\mambaforge\lib\ntpath.py", line 703, in relpath
raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'
```
signac uses relative paths in several places for user-readable data like log …
> Improve Windows compatibility (safe relative paths, no float128).

- changelog.txt
- contributors.yaml
- doc/api.rst
- signac/contrib/job.py
- tests/test_job.py
Users can access the project which a job belongs to from the job object
Resolves #423
> Access project from job

- changelog.txt
- signac/__main__.py
- tests/test_shell.py
This PR resolves #613 by removing the `--doc-filter` argument from the signac CLI. Users who wish to search by a document filter should replace syntax as shown below:
```bash
Before (simple syntax):
$ signac find --doc-filter a 0
After (simple syntax):
$ signac find doc.a 0
Before (JSON syntax):
$ signac find --doc-filter '{"a": 0}'
After (JSON syntax):
$ signac find '{"doc.a": 0}'
```
The general feature of searching by document filters has been replaced by a generalized filter syntax that prefixes state point keys with `sp.` and document keys with `doc.`. This applies that change from #586 to the CLI.
> Remove --doc-filter option from CLI.

- changelog.txt
- signac/__main__.py
- signac/common/config.py
- signac/contrib/project.py
- tests/test_job.py
- tests/test_project.py
- tests/test_shell.py
This PR deprecates the `read_config_file` and `load_config` APIs, the remaining public components of the config module. As of glotzerlab/signac-flow#649 we have confirmed that higher-level signac projects should be able to interface with configuration information solely via the `Project.config` attribute.
In the interest of simplicity I have not bothered to deprecate methods like `search_tree` and `check_and_fix_permissions` since we have no reason to expect external users to be touching them. I plan to remove them without deprecation in 2.0.
Resolves #753.
> Deprecate config module

- setup.cfg
Removes all filters of warnings during pytests.
These were hardcoded at various points during 1.x development due to ongoing deprecations and other related changes that could not be worked around. They are no longer necessary.
> Stop filtering out warnings.

- signac/__main__.py
- signac/common/config.py
- signac/contrib/migration/v0_to_v1.py
- signac/contrib/migration/v1_to_v2.py
- signac/contrib/project.py
- tests/test_project.py
- tests/test_shell.py
This PR adds a check in project initialization to ensure that projects with old schemas are detected when signac fails to find a project with the current schema. The resulting check provides the user a meaningful error about how to proceed with updating their schema using our migration code. This PR also exposes a CLI for migration to complement the Python interface, providing a simpler and friendlier approach to one-off migration that is recommended by the error.
Necessary to for projects how to migrate to v2.
> Warn users to migrate when old schema is detected and enable migration CLI

- changelog.txt
- signac/common/config.py
This PR deletes config APIs that are deprecated.
Resolves #789. The outstanding question is what to do about the `Config` class and whether it needs to remain public.
> Remove deprecated config APIs.

- signac/contrib/migration/v1_to_v2.py
- tests/test_project.py
Makes the final `os.replace` calls in the v1->v2 migration conditional on whether the files exist so that the script doesn't try to move nonexistent files.
Not every project will have a shell history or a state point cache.
> Only try to move v1 schema files that exist.

- changelog.txt
- signac/core/dict_manager.py
- signac/core/h5store.py
This PR makes `_DictManager` private. Addresses a `TODO` in the code.
> Make _DictManager private.

- setup.cfg
- signac/__main__.py
- tests/test_searchindexer.py
This PR fixes up a few miscellaneous TODO items.
- Ignore vendored `deprecation` in code coverage measurements.
- Remove TODO about `$ signac sync` being untested. This seems to be tested: https://github.com/glotzerlab/signac/blob/bd6575397f1d35527e02254bd5a8ea002108283d/tests/test_shell.py#L424
- Remove TODO about documenting the "no dots in keys" requirement for `_SearchIndexer`. This is already documented: https://github.com/glotzerlab/signac/blob/bd6575397f1d35527e02254bd5a8ea002108283d/signac/contrib/_searchindexer.py#L232
> Miscellaneous TODO items

- tests/test_job.py
- tests/test_project.py
This PR cleans up some unused global variables from test files and makes variable naming more consistent.
One noteworthy change: we need to rename the function `testdata` because pytest is interpreting it as a test based on its name. It is just a helper function that returns a generated random string. This was throwing a warning:
```
tests/test_job.py::testdata
/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but tests/test_job.py::testdata returned '61aed30d-f239-4bae-aa5c-24d122db9017', which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
warnings.warn(
```
> Clean up test files

- signac/_synced_collections/backends/collection_json.py
I think `JSONAttrDict` is supposed to be unlike `JSONDict` in docs. I simply updated the reference.
> Fix JSONAttrDict docstring

- changelog.txt
Removes inaccurate guidance about doc filters being removed in 3.0. Doc filters were removed in 2.0 instead.
> Remove inaccurate guidance about doc filters being removed in 3.0.

- signac/project.py
Adds a better error messgae for calling `project.open_job()`.
Before, it would tell you something that implied you provided both statepoint and id: "Either statepoint or id must be provided, but not both."
I was working on something for dashboard and this more descriptive message would have saved me a little time.
> Add more descriptive error if sp and id are not provided

- doc/conf.py
Removed an unnecessary intersphinx reference that I missed in #924. No changelog needed.
> Remove numcodecs from docs.

- .github/workflows/run-pytest.yml
Oldest tests still remains on Python 3.8. NumPy no longer supports Python3.8 in their latest packages.
> ci: No longer test latest packages on Python 3.8

- CONTRIBUTING.md
The link to the Support section of the docs in the contributing guide was moved. Changed it to the current one.
I don't think updating the changelog is necessary :P
> Fix dead link to the Support documentation

- .github/workflows/run-pytest.yml
- changelog.txt
- pyproject.toml
- requirements/requirements-test-optional.txt
- signac/import_export.py
Add Python 3.12 to CI testing and reduce non-Ubuntu runners to just oldest, minimal, and newest tests.
- Add newest Python version to testing.
- Reduce organization runners required for limited non-Linux OSes.
> Add Python 3.12 and limit MacOS/Window's tests.

- CITATION.cff
> Add Corwin

- CITATION.cff
Small follow-up to #968. I re-ordered this so that active project maintainers are listed together. cc: @cbkerr for awareness.
> Re-order active maintainers.

- CITATION.cff
- changelog.txt
- signac/filterparse.py
- tests/conftest.py
- tests/test_find_command_line_interface.py
- tests/test_shell.py
- fixes bug
- adds test to `test_shell.py`
- I do not fix the testing code in `test_find_command_line_interface.py` that does not properly test the code path but I left a todo for now.
The `$not` expression was broken on the command line. I noticed this while working on https://github.com/glotzerlab/signac-docs/pull/199
signac was inserting `sp.` prefixes before the operator
```bash
$ signac find '{"$not": {"a": 1}}'
Error: "Invalid operator placement 'sp.$not.a'."
```
The function `filterparse._add_prefix` does the inserting, which later triggered an error in `_search_indexer._find_expression`. This code path wasn't tested.
> Fix parsing of $not expression on command line

- changelog.txt
- doc/api.rst
- signac/job.py
- signac/project.py
- tests/test_job.py
- tests/test_numpy_integration.py
- tests/test_project.py
Improve the performance of signac for many use-cases, especially when workspaces have with large job counts. Read the complete commit messages for full details on each change.
To summarize:
* Introduce `Job.statepoint_mapping` (edit: `Job.cached_statepoint`)which allows cached, read-only access to the statepoint. `statepoint_mapping` is loaded on demand when the job is not in the cache.
* Use the statepoint cache in additional code paths.
* All `open_job` code paths now lazily load `Job._statepoint`.
* Add `validate_statepoint` argument to `Job.init`. When `False`, `init` checks only that the job directory exists.
* Cache job ids in `JobsCursor` so that `__len__` and `__contains__` are O(1).
* Re-use the results from `listdir` when iterating over jobs in `Project` and bypass the `exists` …
> Improve performance

- changelog.txt
- requirements/requirements-test-optional.txt
- tests/test_h5store.py
Apply changes from https://numpy.org/doc/stable//numpy_2_0_migration_guide.html#changes-to-namespaces
> Support numpy 2 in tests

- asv.conf.json
- changelog.txt
`asv` 0.6.2 and later changed the default build command, breaking our benchmarks.
This PR defines a `build_command` that appears to work, which is closer to the pre-0.6.2 behavior of `asv`.
See https://github.com/glotzerlab/signac/pull/1017#issuecomment-2634745588 and https://github.com/airspeed-velocity/asv/issues/1453#issuecomment-2645978145.
> Define build command in asv.conf.json to enable support for asv 0.6.2 and later

- contributors.yaml
- signac/project.py
- tests/test_project.py
Implemented `__getitem__` for JobsCursors, allow for indexing and slicing after calling `project.find_jobs()`
`JobsCursors` are iterable through the `_JobsCursorIterator` API, but slicing and indexing was not supported. This is atypical for Python types and requires users to unpack the cursor to index it.
This implementation returns a single `Job` if an integer index is requested, or a `_JobsCursorIterator` if a slice is requested. New tests have been added to cover the new functionality.
> Support `__getitem__` with `JobsCursor` objects
