.github/PULL_REQUEST_TEMPLATE.md
The PR template linked to the code style file in a branch, instead of the version on `master`.
If necessary:
=> Fix link to code style in Pull Request template

signac/core/h5store.py
Expand the H5Store docstrings.
=> Expand the H5Store doc-string documentation.

signac/contrib/project.py, tests/test_project.py
This patch implements the option to "get" a project within a root
directory or above it. That means when get_project(root, search=True),
that is identical to switching into root and calling get_project()
without any arguments.
The main motivation is that it is silly that we need to switch the
working directory in order to be able to search for a project. It will
also simplify the implementatino of the "get_job()" feature.
If necessary:
=> Implement option to get a project within and above a root directory.

.circleci/config.yml
Circle-ci cache rebuilt. This will also fix issues in #118 .
=> Increase circle-ci cache version to v3.

changelog.txt, signac/contrib/project.py, tests/test_project.py
Resolves #38 by adding IPython display capabilities for the `JobsCursor` class.
=> Enable IPython display

tests/test_project.py
Small fix for the attribute name used for pandas Project representation tests.
=> Fix pandas Project representation tests.

.circleci/config.yml, .coveragerc
This PR improves coverage reporting configurations to ignore external modules (e.g. tqdm, six).
If necessary:
=> Improve coverage reporting

README.md
Revising README, improving quick access to key info and visual appeal.
=> README Revisions

signac/contrib/job.py, tests/test_job.py
=> Properly handle Job.move() error conditions.

changelog.txt, doc/api.rst, doc/conf.py, signac/contrib/job.py, signac/contrib/project.py, signac/core/dict_manager.py, signac/core/h5store.py
- Extend documentation of H5Store and H5StoreManager.
- Extend documentation of DictManager.
- Expose JSONDict, H5Store, H5StoreManager in API.
- Misc. fixes and improvements.
=> Various improvements to the documentation.

changelog.txt
- Added missing entries.
- Updated wording.
- Updated order.
- Added highlights.
=> Update changelog for version 1.0.0.

changelog.txt, contributors.txt, signac/contrib/collection.py, tests/test_collection.py
Fixes #164
We find decimal and integer numbers that are mathematically equivalent (e.g., 4 and 4.0) by first checking to see if the value being searched for is an integer (not an `int`, but a "whole" number). If it is, then we do 2 `get`s from the index, one for the `int` value and one for the `float` value. The result in this case is the set union of these two results. 
This issue is described in #164.
If necessary:
=> Find integers and floats of equivalent values

signac/contrib/project.py
Fixed minor typos in Project documentation.
=> Fixed minor project typos.

.github/PULL_REQUEST_TEMPLATE.md
Update pull request template for switch to *OneFlow* branching model.
=> Update pull request template to reflect change of branching model.

.circleci/config.yml
Fix circle-ci caching misconfiguration.
=> Fix circle-ci cache misconfiguration.

requirements-benchmark.txt
To fix incompatibility with newer git versions.
=> Update GitPython to 2.1.11.

changelog.txt, signac/contrib/job.py, signac/contrib/project.py, tests/test_job.py, tests/test_project.py
Extend unit tests to check for identify of `eval(repr(x))` of affected
classes.
=> Fix and improve repr of Project, Job, and JobsCursor.

changelog.txt, signac/contrib/import_export.py, tests/test_shell.py
I updated the path building function created for projects with a single job.
This resolves #208. 
If necessary:
=> Address problem with single job views

.github/PULL_REQUEST_TEMPLATE.md
The link to the list of contributors was wrong (txt instead of yaml).
=> Fix link to list of contributors.

doc/conf.py, doc/support.rst, signac/contrib/errors.py, signac/contrib/project.py
I made a few small fixes to correct warnings/errors in the Sphinx docs.
If necessary:
=> Small documentation fixes in preparation for v1.3.

.gitignore, doc/_static/css/signac-theme.css
Add missing css files from #260.
=> Add missing CSS files.

requirements-benchmark.txt
Fix CI issues related to benchmark step.
=> Pin gitdb version for benchmark requirements.

tests/test_indexing.py
follow to get rigde of warning in #292
If necessary:
=> changing the name of class TestFS to FSTest in test/test_indexing.py

.circleci/config.yml, requirements-dev.txt
Coverage previously failed with Python 3.8. Something has been updated upstream and it now runs successfully.
Resolves #259.
If necessary:
=> Run coverage with Python 3.8.

.circleci/config.yml, .coveragerc, requirements-dev.txt, tests/test_shell.py
This PR implements the first two tasks of issue #297. 
- Added tests and coverage for `__main__.py` , and reached the coverage of about 80%.
#297 
If necessary:
=> Added tests and coverage for CLI

signac/contrib/project.py
A couple docstrings were incomplete.
I didn't know what the `**kwargs` in the signature would do, so I added documentation for them.
If necessary:
=> Improve Project docstrings.

signac/__main__.py
This PR adds a palette emoji 🎨 in the version info in `signac shell`. It's _perfectly fine_ if we choose to reject this for any reason. I don't think this will cause any problems since Python 3 supports Unicode and this is just a Unicode character. I am not putting the emoji in the output of `signac --version` so that the version can be easily parsed from that output string if needed. There are so many packages that use emoji in their git commit messages and other parts of the software so I do not anticipate any issues with locales/etc.
Just for fun. I've been thinking about this for a while. 😄
If necessary:
=> Show a palette emoji 🎨 in signac shell's version info.

changelog.txt, signac/contrib/project.py, tests/test_project.py
=> Added groupby for variable that are not present in entire project

setup.cfg, signac/contrib/linked_view.py, signac/contrib/utility.py, signac/core/utility.py
issue #315  
If necessary:
Change of doc string to `numpydoc` in schema.py
=> numpydoc style(signac/contrib/linked_view.py, signac/contrib/utility.py, signac/core/utility.py)

setup.py
Added some relevant project URLs to `setup.py`
We should make it as easy as possible for users to find all of the URLs associated with the project. These changes will make it easy for someone to find these URLs as they will be listed on [here](https://pypi.org/project/signac/) under project links.
If necessary:
=> Add more URLs to setup.py

setup.cfg, signac/contrib/collection.py
issue #315 
If necessary:
Change of doc string to `numpydoc` in collection.py
=> numpydoc style (signac/contrib/collection.py)

signac/warnings.py
Add a top-level module docstring for signac/warnings.py
If necessary:
=> Fix doc strings for signac/warnings.py

.circleci/config.yml
Updates pip to 20.2. The previous pinned version was getting pretty old.
=> Use pip 20.2.

.circleci/config.yml, changelog.txt, setup.py
Includes Python 3.9 in CI and other small CI updates.
If necessary:
=> Python 3.9, other CI updates.

.circleci/config.yml, changelog.txt
Added MacOS to CircleCI pipeline.
In the past, `test_single_writer_multiple_reader_same_instance` from test_h5store.py, failed on MacOS. Although this test no longer fails on MacOS, including this additional operating system in the CircleCI pipeline will prevent inconsistent behavior across operating systems in the future.
Resolves #281 
If necessary:
=> Added MacOS test to CircleCI pipeline

tests/test_h5store.py
I added some tests for additional data types to H5Store. Written while exploring #419.
Just expands the testing suite a bit.
=> More H5store type tests.

signac/__main__.py, signac/contrib/project.py
I noticed in signac-flow that the function `Project.min_len_unique_id` was being called for every job operation, which made the code much slower because the function is O(N), resulting in an O(N^2) code path.
I decided to add a note to the function here, so that the runtime complexity is more obvious. I am also opening a PR to signac-flow to address the slowdown there.
I also updated `signac find` so it only gets the minimum length of unique id if it will be used. This is the only place where the function was called in the code base (outside of tests).
This shouldn't need a changelog line since it's a minor change to the docs.
If necessary:
=> Document complexity of min_len_unique_id.

.circleci/config.yml, benchmark.py, signac/__main__.py, signac/contrib/import_export.py, signac/contrib/job.py, signac/contrib/linked_view.py, signac/contrib/project.py, signac/contrib/schema.py, signac/diff.py
A few very minor updates to style, variable names, docstrings, and code comments. This moves towards consistency in the framework (many of these changes have been done in signac-flow recently) and it shouldn't require review because the changes are minor and non-breaking. I will merge as soon as tests pass.
- Update _register method.
- Use `job.id` instead of `job._id` and `job_id` instead of `jobid` (excluding cases that would change public APIs).
- Use descriptive variable names.
- Remove extra blank lines.
General cleanup of code.
If necessary:
=> Minor style changes.

.circleci/config.yml
Adds MongoDB and Redis images to the CPython tests so that those tests can run. I did not add them to the Windows, Mac, or PyPy tests. I think this testing is sufficient.
These backends have been implemented since #364 but have required local installations of MongoDB and Redis to test (and can be silently skipped by developers who weren't aware of that). Since the Python package requirements were already being installed as part of CI, adding these images is sufficient to trigger tests.
If necessary:
=> Feature/synced collection/test mongodb redis

signac/core/synced_collections/collection_json.py, signac/core/synced_collections/synced_attr_dict.py, signac/core/synced_collections/synced_collection.py, signac/core/synced_collections/synced_list.py, tests/test_synced_collections/synced_collection_test.py
This PR makes operations on SyncedAttrDict and SyncedList objects thread safe. It provides opt-in mechanisms for thread safety for different backends to support thread-safe execution. It also allows the user to enable or disable thread safety. This feature may be inadvisable in the long term, but is convenient for benchmarking purposes and so will be relevant while we integrate these objects into the core of signac.
Note that this does not address #397, which requires making buffer loads/saves thread safe; that will be addressed in a separate PR once #462 is merged.
If necessary:
=> Feature/synced collection/thread safety

doc/api.rst, signac/core/synced_collections/buffered_collection.py, signac/core/synced_collections/collection_json.py, signac/core/synced_collections/collection_zarr.py, signac/core/synced_collections/file_buffered_collection.py, signac/core/synced_collections/memory_buffered_collection.py, signac/core/synced_collections/serialized_file_buffered_collection.py, tests/test_synced_collections/synced_collection_test.py, tests/test_synced_collections/test_json_buffered_collection.py
Creates a new base class for the two file buffering modes in order to standardize the logic.
These two classes were already very similar, and with #468 they both became more complex and more duplicated. The downside of this PR is that it further extends the inheritance hierarchy, which will make it harder to follow things through the code. However, I think the DRY gains outweigh this complexity, especially since with synced collections the reasons for the different parts of the existing hierarchy are well-documented and somewhat self-evident from the design.
If necessary:
=> Feature/synced collection/unify buffering

signac/core/synced_collections/buffered_collection.py, signac/core/synced_collections/collection_json.py, signac/core/synced_collections/collection_zarr.py, signac/core/synced_collections/file_buffered_collection.py, signac/core/synced_collections/memory_buffered_collection.py, signac/core/synced_collections/serialized_file_buffered_collection.py, signac/core/synced_collections/synced_attr_dict.py, signac/core/synced_collections/synced_collection.py, signac/core/synced_collections/synced_list.py, signac/core/synced_collections/utils.py, tests/test_synced_collections/synced_collection_test.py, tests/test_synced_collections/test_json_buffered_collection.py
This PR converts all context managers in synced collections from `contextlib.contextmanager` to custom classes.
Resolves #465. Using `contextlib.contextmanager` can have considerable overhead, so it's worthwhile to avoid. I should note that most of my benchmarks were not sensitive enough to capture such performance losses, since in general the contents of context managers outweigh the overhead of the context itself. Moreover, a number of different context managers throughout the code base follow a simple counting based paradigm that is now encoded in a pair of standardized classes in the utils module.
If necessary:
=> Feature/synced collection/contexts

doc/api.rst, signac/contrib/project.py
Adding JobsCursor documentation
Including JobsCursor in the `api.rst` file
The JobsCursor class was not included in our api documentation, so methods like `to_dataframe` were not documented at all.
Note: I'm not sure how to handle redundant docstrings between `Project` and `JobsCursor`. Should we document everything in `JobsCursor` and just have `Project` link to it? If so, how much information should we still include so that things like previews in text editors are still complete?
Also, I plan to make a PR to `signac-docs` to have an example for how to use pandas efficiently with signac, similar to the Sacred example.
If necessary:
=> adding documentation for JobsCursor api

signac/contrib/collection.py, signac/contrib/filterparse.py, signac/contrib/import_export.py, signac/contrib/project.py, signac/core/json.py, tests/test_find_command_line_interface.py
Deprecates the internal json module in signac and changes all non-deprecated modules to import the built-in json module instead of signac's.
This module is unnecessary now that the special json serialization is isolated to synced collections. Having a module name conflict with the standard library is also undesirable, so removing this is beneficial in that respect as well.
If necessary:
=> Deprecate json module

.github/workflows/auto-merge.yml
This will auto-merge dependbot PRs (not major bumps but minor and patch) if the tests pass.
=> auto merge patches and minor versions

doc/conf.py
Updates URLs for intersphinx references in the documentation. This can be merged immediately.
If necessary:
=> Update intersphinx links

signac/__main__.py
Use a context manager to ensure that index file is closed after read.
Resolves #496.
This fix is not the most efficient (converts a generator to a list comprehension), but since index-related APIs are slowly being removed anyway this is not a priority. Since it's a purely internal function I also don't think a changelog entry is warranted.
If necessary:
=> Read entire index contents then close index file.

changelog.txt, signac/contrib/filterparse.py, signac/contrib/import_export.py, signac/contrib/linked_view.py, signac/contrib/project.py, signac/contrib/schema.py, tests/test_find_command_line_interface.py, tests/test_project.py, tests/test_shell.py
=> Revert "Implement feature to search jobs with a sp- and doc-integrated filter "

signac/contrib/project.py
This change resolves #500 with a temporary backwards-compatibility layer for older versions of signac-flow.
Resolves #500.
If necessary:
=> Allow doc filters to be passed to JobsCursor on construction.

doc/api.rst, signac/__init__.py, signac/contrib/job.py, signac/contrib/project.py, signac/synced_collections/__init__.py, signac/synced_collections/backends/collection_json.py, signac/synced_collections/backends/collection_mongodb.py, signac/synced_collections/backends/collection_redis.py, signac/synced_collections/backends/collection_zarr.py, signac/synced_collections/buffers/buffered_collection.py, signac/synced_collections/data_types/__init__.py, signac/synced_collections/data_types/attr_dict.py, signac/synced_collections/data_types/synced_attr_dict.py, signac/synced_collections/data_types/synced_dict.py, signac/synced_collections/validators.py, tests/test_synced_collections/attr_dict_test.py, tests/test_synced_collections/synced_collection_test.py, tests/test_synced_collections/test_json_buffered_collection.py, tests/test_synced_collections/test_json_collection.py, tests/test_synced_collections/test_validators.py
This change removes attribute-based access from `SyncedDict` and confines it to a new mixin class `AttrDict`. This class is no longer inherited from by most backends, only a few newly created JSON classes that will use this for signac.
This PR will have some conflicts with #503, but hopefully not too many.
This change was precipitated by some the [benchmarks](https://github.com/glotzerlab/signac/pull/484#issuecomment-774398330) of #484 implicating the deep hierarchy and a slow `__setattr__` implementation in Python with slowing down certain performance-critical operations like opening many signac jobs by id. Additionally, overriding attribute access in this manner is error-prone and makes it harder to extend these classes, so it's in our best interest to avoid this if possible. We must …
=> Feature/synced collection/remove attr access

signac/contrib/job.py
Rather than using `os.path.join`, directly concatenating using `os.sep` in `job.workspace` and `job._statepoint_filename`. All the inputs are completely controlled by signac, so we should not need any of the fancier handling done by `os.path.join` to avoid duplicate slashes, handle multiple absolute paths, etc. For the straightforward cases we're dealing with, the simple string concatenation with `os.sep` should be faster without loss of generality.
Optimization for synced collections.
If necessary:
=> Don't use os.path.join where not needed.

signac/contrib/job.py, signac/synced_collections/backends/collection_json.py, signac/synced_collections/data_types/synced_list.py, signac/synced_collections/numpy_utils.py, signac/synced_collections/utils.py, signac/synced_collections/validators.py, tests/test_synced_collections/test_utils.py, tests/test_synced_collections/test_validators.py
Add a single validator for all JSONAttrDict types that checks all the necessary conditions.
Since validators operate recursively on entire data structures, calling multiple validators is expensive. Using a single validator that checks all conditions on a single pass through the data structure significantly reduces time spent on validation.
If necessary:
=> Feature/synced collection/optimize jsondict validation

signac/synced_collections/data_types/synced_collection.py, signac/synced_collections/numpy_utils.py
This PR applies a number of minor optimizations, in particular a faster exit from the `_from_base` method and a more efficient `SyncedCollection.__init__`.
Optimizing synced collections.
If necessary:
=> Feature/synced collection/optimize

doc/cli.rst, doc/conf.py
1. alphabetized the list of commands
2. grouped in categorize via linking at top of file for new users
See #360
I thought it would be confusing to impose the grouping on the sidebar.
Reason 1: experienced users know what command they are looking up and alphabetical helps that.
Reason 2: new users might click on the name "Command Line Interface"  in the sidebar and be taken to the top of the page
If necessary:
=> Group CLI commands by linking

.circleci/deploy.bash
Uses PyPI tokens for authentication.
The current username and password is outdated and @b-butler has added a token to the CircleCI environment.
:warning: *This will be tested during the next release.*
If necessary:
=> Use PyPI tokens for authentication.

README.md, doc/support.rst
Point users to Slack for support. We don't actively monitor Gitter as much.
If necessary:
=> Point users to Slack for support.

signac/contrib/job.py, signac/contrib/project.py, signac/sync.py
I was playing with some automated refactoring tools. While I don't want to use the tool, it did find some ways to improve the clarity of some conditions/statements in the codebase.
If necessary:
=> Small refactors for clearer logic.

signac/contrib/utility.py
Removes deprecated utility functions/classes.
signac 2.0 cleanup.
If necessary:
=> Remove deprecated utility functions/classes.

signac/common/config.py, signac/common/validate.py
Removes `[hosts]` section from signac configuration.
I made some internal functions private. We could probably be more aggressive with making functions private in a later pass through the code base.
Resolves issue #590. See that issue for details.
If necessary:
=> Remove hosts validators

changelog.txt, signac/contrib/project.py
addresses #588, deprecating index arguments in project.py since we are removing indexing in v 2.0
If necessary:
=> adding deprecation warnings for index arguments

signac/contrib/filterparse.py, tests/test_shell.py
Signac interprets `signac find x '[0, 1, 0]'` as `'{"x": "[0, 1, 0]"}'`. The PR ensures signac interprets `signac find x '[0, 1, 0]'` as `'{"x": [0, 1, 0]}'`.
Fixes #615 
If necessary:
=> Fix bug for when CLI signac find command used with lists

.readthedocs.yaml, doc/conf.py, doc/requirements.txt
A small bit of maintenance/updates/cleanup. I will merge when tests and RTD documentation builds pass.
=> Update ReadTheDocs requirements.

.circleci/config.yml, changelog.txt, requirements/requirements-test-optional.txt, setup.py, tests/test_shell.py
Add Python 3.10 support.
If necessary:
=> Python3.10

signac/__main__.py, signac/common/config.py, signac/contrib/migration/__init__.py, signac/contrib/project.py, tests/test_job.py, tests/test_project.py
This PR removes `config.get_config`, which can be replaced by using `config.read_config_file` directly, and makes `search_standard_dirs` an internal function. If this PR is approved I will make a corresponding deprecation PR for master.
Reducing cruft for 2.0. This change was extracted from #643.
If necessary:
=> Remove unnecessary config APIs

changelog.txt, signac/__main__.py, signac/common/config.py, signac/contrib/project.py, tests/test_job.py, tests/test_project.py
This PR deprecates the config APIs removed on next in #674. I went with the simplest possible deprecation method of implementing an internal method called by the existing methods since all of these have already been removed on next with the appropriate changes, so limiting this PR's changeset minimizes conflicts when it is merged down.
Prep for 2.0
If necessary:
=> Deprecate unnecessary config APIs

signac/contrib/project.py, signac/synced_collections/backends/collection_json.py, signac/synced_collections/buffers/file_buffered_collection.py, signac/synced_collections/data_types/synced_dict.py, signac/synced_collections/validators.py, tests/test_synced_collections/synced_collection_test.py
I added issues for TODOs in the repo and added the issue numbers to the in-line TODOs
=> adding issue numbers

changelog.txt, signac/__main__.py, signac/contrib/job.py, signac/contrib/project.py, tests/test_job.py, tests/test_project.py
Replaces `_id` with `id_` when used as a variable (but not as a private attribute). This PR replaces #681, #680.
This work was completed by @parisatork but I didn't have permissions to rebase and force-push onto #681 so I created a new PR.
Resolves #679.
=> Replace _id with id_

contributors.yaml
=> Add PT to contributors

.circleci/config.yml, tests/test_synced_collections/synced_collection_test.py
This PR changes the way that we upload coverage results to CircleCI's new preferred method. It also changes CI so that we only upload coverage results on a single run rather than for all of them.
Resolves #630.
=> Use orbs for codecov.

doc/api.rst, signac/contrib/job.py, signac/core/dict_manager.py, signac/core/h5store.py
A handful of documentation fixes.
=> Some minor documentation fixes.

doc/api.rst, doc/cli.rst, doc/index.rst
Updates the documentation for the `next` branch to reflect recent API changes.
=> Update 2.0 docs.

signac/contrib/_searchindexer.py, signac/contrib/filterparse.py, signac/contrib/import_export.py, signac/contrib/job.py, signac/contrib/linked_view.py, signac/contrib/project.py, signac/contrib/schema.py, signac/contrib/utility.py, signac/sync.py, signac/synced_collections/buffers/memory_buffered_collection.py, signac/synced_collections/data_types/synced_dict.py, signac/synced_collections/data_types/synced_list.py, signac/syncutil.py, signac/testing.py
Resolves #344. Note: I am going to open a couple more PRs with related docstring revisions that may require more thoughtful review. This PR is a subset that should be non-controversial and easy to approve.
=> Add "optional" to parameter docstrings.

signac/contrib/import_export.py
While working on #763, I worked on improving the docs for import-export logic.
I also removed the helper method `_parse_workspaces` and inlined its function as `read_statepoint_file` in `_analyze_directory_for_import`. This makes all the `_analyze_*` methods have a similar structure.
=> Refactor import-export logic and update docs.

signac/contrib/project.py
Resolves #744.
Clarifies docs. No changelog required.
=> Clarify behavior of groupby default=None.

signac/contrib/project.py
See https://github.com/glotzerlab/signac/pull/817#issuecomment-1251342595
Fixes docs.
=> Use Yields in groupby docs.

benchmark.py, changelog.txt, setup.cfg, signac/contrib/indexing.py, signac/contrib/job.py, signac/contrib/project.py, signac/core/utility.py, signac/sync.py, tests/test_indexing.py, tests/test_job.py, tests/test_project.py, tests/test_temporary_project.py, tests/test_versioning.py
Fix deprecation warnings for the 1.8.0 release.
Needed for #819.
=> Fix 1.8 deprecations

benchmarks/__init__.py, benchmarks/benchmarks.py, cov.sh, doc/requirements.txt, setup.cfg
Tackles a few cleanup items from #844.
=> Cleanup post-merge 2.0

changelog.txt, signac/__main__.py, signac/common/config.py, signac/contrib/project.py, tests/test_shell.py
Refactors `_Config` to be private and have a minimal API. Also makes a few helper functions private.
=> Refactor _Config class.

.pre-commit-config.yaml, .sync-zenodo-metadata.py, signac/h5store.py, signac/import_export.py, tests/test_diff.py, tests/test_h5store.py, tests/test_job.py, tests/test_project.py, tests/test_searchindexer.py, tests/test_synced_collections/test_json_buffered_collection.py, tests/test_synced_collections/test_json_collection.py, tests/test_synced_collections/test_mongodb_collection.py, tests/test_synced_collections/test_redis_collection.py, tests/test_synced_collections/test_zarr_collection.py
Update `pre-commit` hooks to avoid `isort` installation errors and update `black` to the latest version.
To fix CI tests.
=> Update pre-commit hooks for black and isort.

.github/workflows/publish-packages.yml, .github/workflows/run-pytest.yml, .pre-commit-config.yaml, requirements/requirements-test-optional.txt, requirements/requirements-test.txt
Updates GitHub Actions and dependency versions.
PRs #898 and #900 were closed because code coverage dropped. However, it appears this was due to a rate limit (either from GitHub or Codecov) preventing some coverage reports from being uploaded. I have created a new secret `CODECOV_TOKEN` for this repository so that it is used instead of the default Codecov "public repo" token which appears to be rate-limited. See https://github.com/codecov/codecov-action/issues/557.
=> Update GitHub Actions and dependency versions.

.github/workflows/publish-packages.yml, .github/workflows/run-pytest.yml
=> Use Python 3.11 for package releases, enable 3.11 testing with newest dependencies.

.pre-commit-config.yaml, .zenodo.json, changelog.txt
I ran through some of the "update" steps for making a release. This PR should help reduce the diff in the actual release branch / PR.
=> Pre-release 2.0.0

README.md
Resolves #912.
The example commands in the `README` needed an update for signac 2.0.
=> Fix README example init command.

changelog.txt, requirements/requirements-test-optional.txt
Remove ruamel.yaml dependency.
It is not used anywhere in the codebase.
=> Remove ruamel.yaml dependency.

doc/conf.py
These changes are required by readthedocs: https://about.readthedocs.com/blog/2024/07/addons-by-default/
Ensure that the signac documentation continues to build.
=> Address readthedocs deprecations.

doc/support.rst
Replace the `signac-support` email address and slack link with a link to the signac discussion board.
=> Point users to the GitHub discussion board.
